language: python
  
python:
  - "2.7"
#  - "3.4"
#  - "3.5"
  - "3.6"      # current default Python on Travis CI
#  - "3.7"
#  - "3.8"
#  - "3.8-dev"  # 3.8 development branch
#  - "nightly"  # nightly build

before_install:
  - git submodule foreach git checkout master
  - git submodule foreach git pull
  - pip install nose2

# command to install dependencies
install:
  - python setup.py build_ext --inplace
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then mv pygeoda/_libgeoda.*.so pygeoda/_libgeoda.so; fi

# command to run tests
script:
#  - pytest
  - ls ./pygeoda/
  - python -m nose2
